import React, { useState, useEffect } from 'react';
import { ToolPageLayout, CopyButton } from '../../components/ToolPageLayout';

const SerpPreview: React.FC<{ title: string; description: string; url: string }> = ({ title, description, url }) => (
    <div className="p-4 bg-white dark:bg-brand-bg rounded-lg border border-brand-border font-sans">
        <p className="text-sm text-gray-700 dark:text-brand-text-secondary truncate">{url || 'https://www.example.com'}</p>
        <h3 className="text-blue-600 dark:text-blue-500 text-xl truncate hover:underline">{title || 'Meta Title Appears Here'}</h3>
        <p className="text-sm text-gray-600 dark:text-brand-text-secondary">{description || 'This is where your meta description will be shown. Keep it concise and compelling to attract clicks from search results.'}</p>
    </div>
);

const MetaTagGenerator: React.FC = () => {
    const [title, setTitle] = useState('DiceTools | Free Online Tools for Everyone');
    const [description, setDescription] = useState('Unlock your productivity with over 80 powerful, free online tools. From AI magic to PDF mastery, we\'ve got you covered.');
    const [keywords, setKeywords] = useState('online tools, free tools, pdf editor, json formatter');
    const [generatedTags, setGeneratedTags] = useState('');

    useEffect(() => {
        const tags = `<!-- Meta Tags Generated by DiceTools -->\n<title>${title}</title>\n<meta name="description" content="${description}">\n<meta name="keywords" content="${keywords}">`;
        setGeneratedTags(tags);
    }, [title, description, keywords]);
    
    return (
        <ToolPageLayout
            title="Meta Tag Generator"
            description="Create optimized title and description tags for better SEO."
        >
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="space-y-4">
                    <div>
                        <label className="flex justify-between text-sm font-medium text-brand-text-secondary mb-1">
                            <span>Title</span>
                            <span className={title.length > 60 ? 'text-red-500' : ''}>{title.length} / 60</span>
                        </label>
                        <input type="text" value={title} onChange={e => setTitle(e.target.value)} className="w-full p-2 bg-brand-bg border border-brand-border rounded-md" />
                    </div>
                    <div>
                        <label className="flex justify-between text-sm font-medium text-brand-text-secondary mb-1">
                            <span>Description</span>
                            <span className={description.length > 160 ? 'text-red-500' : ''}>{description.length} / 160</span>
                        </label>
                        <textarea value={description} onChange={e => setDescription(e.target.value)} rows={4} className="w-full p-2 bg-brand-bg border border-brand-border rounded-md" />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-brand-text-secondary mb-1">Keywords (Comma-separated)</label>
                        <input type="text" value={keywords} onChange={e => setKeywords(e.target.value)} className="w-full p-2 bg-brand-bg border border-brand-border rounded-md" />
                    </div>
                </div>
                <div className="space-y-4">
                    <h3 className="font-semibold text-brand-text-primary">SERP Preview</h3>
                    <SerpPreview title={title} description={description} url="https://dicetools.com/" />
                    <h3 className="font-semibold text-brand-text-primary">Generated HTML</h3>
                    <div className="relative">
                        <pre className="bg-brand-bg p-4 rounded-md text-sm whitespace-pre-wrap overflow-auto">
                            <code>{generatedTags}</code>
                        </pre>
                        <div className="absolute top-2 right-2">
                             <CopyButton textToCopy={generatedTags} />
                        </div>
                    </div>
                </div>
            </div>
        </ToolPageLayout>
    );
};

export default MetaTagGenerator;