import React from 'react';
import type { Tool } from '../types';
import GenericAiUnavailableTool from '../pages/GenericAiUnavailableTool'; // Import the generic component

// Icon Components
const AiIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2L9.5 9.5 2 12l7.5 2.5L12 22l2.5-7.5L22 12l-7.5-2.5z"/></svg>;
const PdfIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>;
const TextIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 6.1H3"/><path d="M21 12.1H3"/><path d="M15.1 18.1H3"/></svg>;
const ConverterIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m16 3 3 3-7 7-3 3-3-3 7-7 3-3"/><path d="m2 22 3-3"/><path d="m19 5-7 7"/></svg>;
const DeveloperIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>;
const UtilityIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 0 2l-.15.08a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1 0 2l.15-.08a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>;
const MiscIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>;
const StudentIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c0 1.66 4 3 6 3s6-1.34 6-3v-5"/></svg>;
const SeoIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18"/><path d="M18.7 8l-5.1 5.2-2.8-2.7L7 14.3"/></svg>;
const HairstyleIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 13v-1a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v1"/><path d="M4 12v-1a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1"/><path d="M4 8V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1"/><path d="M4 17v-1a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1"/><path d="M4 21v-1a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1"/><path d="M12 21v-8"/></svg>;


export const tools: Tool[] = [
  // AI Tools - Image/Video generation tools are unavailable as OpenRouter is not an image/video generation API.
  { path: '/hq-image-generator', name: 'AI Image Concept Generator', description: 'Generate detailed textual concepts for images based on prompts using OpenRouter.', category: 'AI', component: React.lazy(() => import('../pages/developer/ImageGenerator')), keywords: ['ai', 'image', 'concept', 'generator', 'art', 'create', 'openrouter'], icon: <AiIcon/> },
  { path: '/text-to-image-generator', name: 'AI Text to Image Concept', description: 'Create stunning textual descriptions for images from text prompts using OpenRouter.', category: 'AI', component: React.lazy(() => import('../pages/developer/TextToImageGenerator')), keywords: ['ai', 'image', 'concept', 'generator', 'text to image', 'art', 'dalle', 'midjourney', 'openrouter'], icon: <AiIcon/> },
  { path: '/ai-image-editor', name: 'AI Image Stylizer', description: 'Apply artistic styles and effects to your image concepts using text prompts (Currently Unavailable).', category: 'AI', component: GenericAiUnavailableTool, keywords: ['ai', 'image', 'style', 'stylizer', 'art', 'filter', 'effects'], icon: <AiIcon/> },
  { path: '/ai-video-generator', name: 'AI Video Generator', description: 'Create high-quality videos from text prompts or images (Currently Unavailable).', category: 'AI', component: GenericAiUnavailableTool, keywords: ['ai', 'video', 'generator', 'motion', 'clip'], icon: <AiIcon/> },
  { path: '/ai-hairstyle-try-on', name: 'AI Hairstyle Concept Generator', description: 'Generate textual concepts of people with different hairstyles and colors from an uploaded image using OpenRouter.', category: 'AI', component: React.lazy(() => import('../pages/ai/HairstyleTryOn')), keywords: ['ai', 'hairstyle', 'hair', 'portrait', 'beauty', 'style', 'fashion', 'generator', 'openrouter'], icon: <HairstyleIcon/> },
  { path: '/lorem-ipsum-generator', name: 'Placeholder Text Generator', description: 'Generate realistic placeholder text for design mockups.', category: 'Text', component: React.lazy(() => import('../pages/text/LoremIpsumGenerator')), keywords: ['placeholder', 'text', 'generator', 'design', 'filler'], icon: <TextIcon/> },

  // PDF Tools - AI-dependent tools updated to use OpenRouter or marked unavailable
  { path: '/pdf-to-word', name: 'AI PDF to Word Converter', description: 'Let AI extract PDF content and layout into an editable format using OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToWordConverter')), keywords: ['pdf', 'word', 'converter', 'doc', 'docx', 'document', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-to-excel', name: 'AI PDF to Excel Converter', description: 'Let AI extract tables from your PDF into a downloadable CSV file using OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToExcelConverter')), keywords: ['pdf', 'excel', 'converter', 'xls', 'xlsx', 'spreadsheet', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-to-powerpoint', name: 'AI PDF to PowerPoint Converter', description: 'Let AI analyze PDF content and structure it for presentations using OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToPowerPointConverter')), keywords: ['pdf', 'powerpoint', 'converter', 'ppt', 'pptx', 'presentation', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-to-image', name: 'PDF to Image Converter', description: 'Convert PDF pages into high-quality images (JPG, PNG).', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToImageConverter')), keywords: ['pdf', 'image', 'converter', 'jpg', 'jpeg', 'png'], icon: <PdfIcon/> },
  { path: '/pdf-merge', name: 'PDF Merge', description: 'Combine multiple PDF files into a single document.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfMerge')), keywords: ['pdf', 'merge', 'combine', 'join'], icon: <PdfIcon/> },
  { path: '/pdf-split', name: 'PDF Split', description: 'Extract specific pages or page ranges from a PDF file.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfSplit')), keywords: ['pdf', 'split', 'extract', 'separate'], icon: <PdfIcon/> },
  { path: '/pdf-compressor', name: 'PDF Compressor', description: 'Reduce the file size of your PDF documents.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfCompressor')), keywords: ['pdf', 'compress', 'reduce', 'size', 'optimizer'], icon: <PdfIcon/> },
  { path: '/pdf-editor', name: 'PDF Text Editor', description: 'Edit text directly in your PDF files while preserving layout.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfTextEditor')), keywords: ['pdf', 'editor', 'edit', 'text', 'inline'], icon: <PdfIcon/> },
  { path: '/pdf-password-protect', name: 'PDF Password Protect', description: 'Add a password to your PDF to secure it.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfPasswordProtect')), keywords: ['pdf', 'password', 'protect', 'secure', 'encrypt'], icon: <PdfIcon/> },
  { path: '/pdf-unlock', name: 'PDF Unlock', description: 'Remove password protection from a PDF file.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfUnlock')), keywords: ['pdf', 'unlock', 'remove password', 'decrypt'], icon: <PdfIcon/> },
  { path: '/pdf-watermark-adder', name: 'PDF Watermark Adder', description: 'Add a text or image watermark to your PDF.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfWatermarkAdder')), keywords: ['pdf', 'watermark', 'add', 'text', 'image'], icon: <PdfIcon/> },
  { path: '/pdf-page-rotator', name: 'PDF Page Rotator', description: 'Rotate pages in your PDF document.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfPageRotator')), keywords: ['pdf', 'rotate', 'page', 'orientation'], icon: <PdfIcon/> },
  { path: '/pdf-page-deleter', name: 'PDF Page Deleter', description: 'Remove specific pages from your PDF file.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfPageDeleter')), keywords: ['pdf', 'delete', 'page', 'remove'], icon: <PdfIcon/> },
  { path: '/pdf-page-extractor', name: 'PDF Page Extractor', description: 'Create a new PDF from selected pages of a document.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfPageExtractor')), keywords: ['pdf', 'extract', 'page'], icon: <PdfIcon/> },
  { path: '/pdf-to-html', name: 'AI PDF to HTML Converter', description: 'Use AI to convert your PDFs into structured HTML files using OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToHtmlConverter')), keywords: ['pdf', 'html', 'converter', 'webpage', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-to-text', name: 'PDF to Text Converter', description: 'Extract plain text from your PDF files.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfToTextConverter')), keywords: ['pdf', 'text', 'converter', 'txt'], icon: <PdfIcon/> },
  { path: '/pdf-form-filler', name: 'PDF Form Filler', description: 'Fill out PDF forms online without any software.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfFormFiller')), keywords: ['pdf', 'form', 'filler', 'fill'], icon: <PdfIcon/> },
  { path: '/pdf-form-creator', name: 'PDF Form Creator', description: 'Create fillable forms in your PDF documents.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfFormCreator')), keywords: ['pdf', 'form', 'creator', 'create', 'fillable'], icon: <PdfIcon/> },
  { path: '/pdf-metadata-editor', name: 'PDF Metadata Editor', description: 'View and edit PDF metadata like author and title.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfMetadataEditor')), keywords: ['pdf', 'metadata', 'editor', 'properties', 'author', 'title'], icon: <PdfIcon/> },
  { path: '/pdf-redaction-tool', name: 'PDF Redaction Tool', description: 'Permanently remove sensitive information from PDFs.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfRedactionTool')), keywords: ['pdf', 'redact', 'censor', 'blackout', 'sensitive'], icon: <PdfIcon/> },
  { path: '/pdf-comparison-tool', name: 'PDF Comparison Tool', description: 'Compare two PDF files and highlight the differences.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfComparisonTool')), keywords: ['pdf', 'compare', 'comparison', 'diff', 'difference'], icon: <PdfIcon/> },
  { path: '/pdf-ocr', name: 'AI PDF OCR (Text Recognition)', description: 'Extract text from scanned PDFs using AI, with layout preservation via OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfOcr')), keywords: ['pdf', 'ocr', 'optical character recognition', 'scan', 'text', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-bookmark-adder', name: 'AI PDF Table of Contents Generator', description: 'Automatically generate a text-based table of contents for your PDF using OpenRouter.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfBookmarkAdder')), keywords: ['pdf', 'bookmark', 'add', 'navigation', 'outline', 'toc', 'ai', 'openrouter'], icon: <PdfIcon/> },
  { path: '/pdf-size-optimizer', name: 'PDF Size Optimizer', description: 'Optimize PDF file size with advanced options.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/PdfSizeOptimizer')), keywords: ['pdf', 'size', 'optimizer', 'compress', 'reduce'], icon: <PdfIcon/> },
  { path: '/batch-pdf-processor', name: 'Batch PDF Processor', description: 'Apply actions like compress or convert to multiple PDFs at once.', category: 'PDF', component: React.lazy(() => import('../pages/pdf/BatchPdfProcessor')), keywords: ['pdf', 'batch', 'process', 'multiple', 'bulk'], icon: <PdfIcon/> },

  // Student Tools
  { path: '/word-counter', name: 'Word Counter', description: 'Count words, characters, sentences, and paragraphs in your text.', category: 'Student', component: React.lazy(() => import('../pages/text/WordCounter')), keywords: ['word', 'character', 'count', 'paragraph', 'student'], icon: <StudentIcon/> },
  { path: '/character-counter', name: 'Character Counter', description: 'Count characters with and without spaces.', category: 'Student', component: React.lazy(() => import('../pages/text/CharacterCounter')), keywords: ['character', 'count', 'text', 'student'], icon: <StudentIcon/> },
  { path: '/gpa-calculator', name: 'GPA Calculator', description: 'Calculate your Grade Point Average.', category: 'Student', component: React.lazy(() => import('../pages/utility/GpaCalculator')), keywords: ['gpa', 'calculator', 'education', 'student'], icon: <StudentIcon/> },
  { path: '/notes-pad', name: 'Notes Pad', description: 'A simple notepad that saves to local storage.', category: 'Student', component: React.lazy(() => import('../pages/misc/NotesPad')), keywords: ['notes', 'pad', 'notepad', 'student'], icon: <StudentIcon/> },
  { path: '/todo-list', name: 'To-Do List', description: 'A simple to-do list manager.', category: 'Student', component: React.lazy(() => import('../pages/misc/TodoList')), keywords: ['todo', 'list', 'tasks', 'student'], icon: <StudentIcon/> },
  { path: '/percentage-calculator', name: 'Percentage Calculator', description: 'Calculate percentages easily.', category: 'Student', component: React.lazy(() => import('../pages/utility/PercentageCalculator')), keywords: ['percentage', 'calculator', 'math', 'student'], icon: <StudentIcon/> },
  { path: '/unit-converter', name: 'Unit Converter', description: 'A universal unit converter.', category: 'Student', component: React.lazy(() => import('../pages/utility/UnitConverter')), keywords: ['unit', 'converter', 'universal', 'student'], icon: <StudentIcon/> },
  { path: '/countdown-timer', name: 'Countdown Timer', description: 'Set a timer for any event.', category: 'Student', component: React.lazy(() => import('../pages/utility/CountdownTimer')), keywords: ['countdown', 'timer', 'clock', 'student'], icon: <StudentIcon/> },
  { path: '/stopwatch', name: 'Stopwatch', description: 'A simple online stopwatch.', category: 'Student', component: React.lazy(() => import('../pages/utility/Stopwatch')), keywords: ['stopwatch', 'timer', 'lap', 'student'], icon: <StudentIcon/> },

  // Text Tools
  { path: '/case-converter', name: 'Case Converter', description: 'Convert text to uppercase, lowercase, title case, and more.', category: 'Text', component: React.lazy(() => import('../pages/text/CaseConverter')), keywords: ['case', 'converter', 'uppercase', 'lowercase'], icon: <TextIcon/> },
  { path: '/remove-line-breaks', name: 'Remove Line Breaks', description: 'Remove unwanted line breaks from your text.', category: 'Text', component: React.lazy(() => import('../pages/text/RemoveLineBreaks')), keywords: ['line break', 'remove', 'paragraph'], icon: <TextIcon/> },
  { path: '/text-repeater', name: 'Text Repeater', description: 'Repeat a piece of text multiple times.', category: 'Text', component: React.lazy(() => import('../pages/text/TextRepeater')), keywords: ['text', 'repeater', 'duplicate'], icon: <TextIcon/> },
  { path: '/base64-encode-decode', name: 'Base64 Encode/Decode', description: 'Encode to or decode from Base64.', category: 'Text', component: React.lazy(() => import('../pages/text/Base64Tool')), keywords: ['base64', 'encode', 'decode'], icon: <TextIcon/> },
  { path: '/url-encoder-decoder', name: 'URL Encoder/Decoder', description: 'Encode or decode URLs.', category: 'Text', component: React.lazy(() => import('../pages/text/UrlEncoder')), keywords: ['url', 'encode', 'decode', 'uri'], icon: <TextIcon/> },
  { path: '/text-separator', name: 'Text Separator', description: 'Separate text by a custom delimiter.', category: 'Text', component: React.lazy(() => import('../pages/text/TextSeparator')), keywords: ['text', 'separator', 'delimiter'], icon: <TextIcon/> },
  { path: '/reverse-text', name: 'Reverse Text', description: 'Reverse the characters in your text.', category: 'Text', component: React.lazy(() => import('../pages/text/ReverseText')), keywords: ['reverse', 'text', 'string'], icon: <TextIcon/> },
  
  // Converters
  { path: '/length-converter', name: 'Length Converter', description: 'Convert between different units of length.', category: 'Converters', component: React.lazy(() => import('../pages/converters/LengthConverter')), keywords: ['length', 'converter', 'units'], icon: <ConverterIcon/> },
  { path: '/weight-converter', name: 'Weight Converter', description: 'Convert between different units of weight.', category: 'Converters', component: React.lazy(() => import('../pages/converters/WeightConverter')), keywords: ['weight', 'converter', 'mass'], icon: <ConverterIcon/> },
  { path: '/temperature-converter', name: 'Temperature Converter', description: 'Convert between Celsius, Fahrenheit, and Kelvin.', category: 'Converters', component: React.lazy(() => import('../pages/converters/TemperatureConverter')), keywords: ['temperature', 'converter', 'celsius'], icon: <ConverterIcon/> },
  { path: '/speed-converter', name: 'Speed Converter', description: 'Convert between different units of speed.', category: 'Converters', component: React.lazy(() => import('../pages/converters/SpeedConverter')), keywords: ['speed', 'converter', 'velocity'], icon: <ConverterIcon/> },
  { path: '/time-converter', name: 'Time Converter', description: 'Convert between different units of time.', category: 'Converters', component: React.lazy(() => import('../pages/converters/TimeConverter')), keywords: ['time', 'converter', 'duration'], icon: <ConverterIcon/> },
  { path: '/currency-converter', name: 'Currency Converter', description: 'Convert between currencies with mock rates.', category: 'Converters', component: React.lazy(() => import('../pages/converters/CurrencyConverter')), keywords: ['currency', 'converter', 'exchange'], icon: <ConverterIcon/> },
  { path: '/number-to-words', name: 'Number to Words', description: 'Convert numbers into words.', category: 'Converters', component: React.lazy(() => import('../pages/converters/NumberToWordsConverter')), keywords: ['number', 'words', 'converter'], icon: <ConverterIcon/> },
  { path: '/binary-to-decimal', name: 'Number Base Converter', description: 'Convert between binary, octal, decimal, and hexadecimal systems.', category: 'Converters', component: React.lazy(() => import('../pages/converters/BinaryToDecimalConverter')), keywords: ['binary', 'decimal', 'converter', 'hex', 'octal'], icon: <ConverterIcon/> },
  { path: '/roman-numeral-converter', name: 'Roman Numeral Converter', description: 'Convert numbers to and from Roman numerals.', category: 'Converters', component: React.lazy(() => import('../pages/converters/RomanNumeralConverter')), keywords: ['roman', 'numeral', 'converter'], icon: <ConverterIcon/> },
  { path: '/json-to-csv', name: 'JSON to CSV Converter', description: 'Convert JSON data to CSV format.', category: 'Converters', component: React.lazy(() => import('../pages/converters/JsonToCsvConverter')), keywords: ['json', 'csv', 'converter'], icon: <ConverterIcon/> },

  // Developer Tools
  { path: '/json-formatter', name: 'JSON Formatter', description: 'Format and validate JSON data.', category: 'Developer', component: React.lazy(() => import('../pages/developer/JsonFormatter')), keywords: ['json', 'formatter', 'validator'], icon: <DeveloperIcon/> },
  { path: '/html-formatter', name: 'HTML Formatter', description: 'Beautify your HTML code.', category: 'Developer', component: React.lazy(() => import('../pages/developer/HtmlFormatter')), keywords: ['html', 'formatter', 'beautify'], icon: <DeveloperIcon/> },
  { path: '/javascript-minifier', name: 'JavaScript Minifier', description: 'Minify JavaScript code to reduce file size.', category: 'Developer', component: React.lazy(() => import('../pages/developer/JsMinifier')), keywords: ['javascript', 'minifier', 'compress'], icon: <DeveloperIcon/> },
  { path: '/css-minifier', name: 'CSS Minifier', description: 'Minify CSS code to reduce file size.', category: 'Developer', component: React.lazy(() => import('../pages/developer/CssMinifier')), keywords: ['css', 'minifier', 'compress'], icon: <DeveloperIcon/> },
  { path: '/color-picker', name: 'Color Picker', description: 'Pick colors and get their codes in various formats.', category: 'Developer', component: React.lazy(() => import('../pages/developer/ColorPicker')), keywords: ['color', 'picker', 'hex', 'rgb'], icon: <DeveloperIcon/> },
  { path: '/regex-tester', name: 'Regex Tester', description: 'Test your regular expressions.', category: 'Developer', component: React.lazy(() => import('../pages/developer/RegexTester')), keywords: ['regex', 'tester', 'regular expression'], icon: <DeveloperIcon/> },
  { path: '/hash-generator', name: 'Hash Generator', description: 'Generate MD5 and SHA hashes.', category: 'Developer', component: React.lazy(() => import('../pages/developer/HashGenerator')), keywords: ['hash', 'generator', 'md5', 'sha'], icon: <DeveloperIcon/> },
  { path: '/ip-finder', name: 'IP Finder', description: 'Find your public IP address.', category: 'Developer', component: React.lazy(() => import('../pages/developer/IpFinder')), keywords: ['ip', 'address', 'finder'], icon: <DeveloperIcon/> },
  { path: '/uuid-generator', name: 'UUID Generator', description: 'Generate universally unique identifiers.', category: 'Developer', component: React.lazy(() => import('../pages/developer/UuidGenerator')), keywords: ['uuid', 'guid', 'generator'], icon: <DeveloperIcon/> },
  { path: '/qr-code-generator', name: 'QR Code Generator', description: 'Generate QR codes from text.', category: 'Developer', component: React.lazy(() => import('../pages/developer/QrCodeGenerator')), keywords: ['qr code', 'generator'], icon: <DeveloperIcon/> },
  
  // SEO Tools - AI-dependent tools updated to use OpenRouter or marked unavailable
  { path: '/keyword-research-tool', name: 'AI Keyword Research Tool', description: 'Get AI-driven insights including search intent, difficulty, volume, and CPC via OpenRouter.', category: 'SEO', component: React.lazy(() => import('../pages/seo/KeywordResearchTool')), keywords: ['seo', 'keyword', 'research', 'volume', 'difficulty', 'ai', 'openrouter'], icon: <SeoIcon/> },
  { path: '/meta-tag-generator', name: 'Meta Tag Generator', description: 'Create optimized title and description tags for better SEO.', category: 'SEO', component: React.lazy(() => import('../pages/seo/MetaTagGenerator')), keywords: ['seo', 'meta', 'title', 'description', 'tags'], icon: <SeoIcon/> },
  { path: '/sitemap-generator', name: 'Sitemap Generator', description: 'Instantly generate an XML sitemap for your website.', category: 'SEO', component: React.lazy(() => import('../pages/seo/SitemapGenerator')), keywords: ['seo', 'sitemap', 'xml', 'generator', 'crawler'], icon: <SeoIcon/> },
  { path: '/backlink-checker', name: 'AI Backlink Checker', description: 'Get an AI-powered analysis of a domain\'s backlink profile (conceptual research via OpenRouter).', category: 'SEO', component: React.lazy(() => import('../pages/seo/BacklinkChecker')), keywords: ['seo', 'backlink', 'checker', 'domain', 'authority', 'ai', 'openrouter'], icon: <SeoIcon/> },
  { path: '/website-analyzer', name: 'AI Website SEO Analyzer', description: 'Get an AI-powered SEO score and optimization report for your website (conceptual analysis via OpenRouter).', category: 'SEO', component: React.lazy(() => import('../pages/seo/WebsiteAnalyzer')), keywords: ['seo', 'analyzer', 'report', 'score', 'audit', 'ai', 'openrouter'], icon: <SeoIcon/> },
  { path: '/robots-txt-generator', name: 'Robots.txt Generator', description: 'Create SEO-friendly robots.txt files easily.', category: 'SEO', component: React.lazy(() => import('../pages/seo/RobotsTxtGenerator')), keywords: ['seo', 'robots.txt', 'generator', 'crawler', 'rules'], icon: <SeoIcon/> },
  { path: '/word-counter-for-seo', name: 'Word Counter for SEO', description: 'Count words and keyword density in content.', category: 'SEO', component: React.lazy(() => import('../pages/seo/WordCounterForSeo')), keywords: ['seo', 'word', 'counter', 'keyword', 'density'], icon: <SeoIcon/> },
  { path: '/broken-link-checker', name: 'AI Broken Link Checker', description: 'Scan a domain for broken or outdated links using AI analysis (conceptual scanning via OpenRouter).', category: 'SEO', component: React.lazy(() => import('../pages/seo/BrokenLinkChecker')), keywords: ['seo', 'link', 'broken', '404', 'checker', 'ai', 'openrouter'], icon: <SeoIcon/> },
  { path: '/domain-authority-checker', name: 'AI Domain Authority Checker', description: 'Get an AI-powered analysis of a domain\'s authority (conceptual analysis via OpenRouter).', category: 'SEO', component: React.lazy(() => import('../pages/seo/DomainAuthorityChecker')), keywords: ['seo', 'domain authority', 'da', 'pa', 'moz', 'ai', 'openrouter'], icon: <SeoIcon/> },
  { path: '/google-serp-preview', name: 'AI Google SERP Preview & Optimizer', description: 'Preview your SERP snippet and get AI-powered recommendations to improve it via OpenRouter.', category: 'SEO', component: React.lazy(() => import('../pages/seo/GoogleSerpPreviewTool')), keywords: ['seo', 'serp', 'preview', 'google', 'title', 'meta', 'ai', 'openrouter'], icon: <SeoIcon/> },
  
  // Utility Tools
  { path: '/age-calculator', name: 'Age Calculator', description: 'Calculate age from date of birth.', category: 'Utility', component: React.lazy(() => import('../pages/utility/AgeCalculator')), keywords: ['age', 'calculator', 'birthday'], icon: <UtilityIcon/> },
  { path: '/bmi-calculator', name: 'BMI Calculator', description: 'Calculate your Body Mass Index.', category: 'Utility', component: React.lazy(() => import('../pages/utility/BmiCalculator')), keywords: ['bmi', 'calculator', 'health'], icon: <UtilityIcon/> },
  { path: '/date-difference-calculator', name: 'Date Difference', description: 'Calculate the difference between two dates.', category: 'Utility', component: React.lazy(() => import('../pages/utility/DateDifferenceCalculator')), keywords: ['date', 'difference', 'calculator'], icon: <UtilityIcon/> },
  { path: '/tip-calculator', name: 'Tip Calculator', description: 'Calculate tips for bills.', category: 'Utility', component: React.lazy(() => import('../pages/utility/TipCalculator')), keywords: ['tip', 'calculator', 'restaurant'], icon: <UtilityIcon/> },
  { path: '/password-generator', name: 'Password Generator', description: 'Generate strong, random passwords.', category: 'Utility', component: React.lazy(() => import('../pages/utility/PasswordGenerator')), keywords: ['password', 'generator', 'security'], icon: <UtilityIcon/> },
  
  // Misc Tools
  { path: '/random-name-generator', name: 'Random Name Generator', description: 'Generate random names.', category: 'Misc', component: React.lazy(() => import('../pages/misc/RandomNameGenerator')), keywords: ['random', 'name', 'generator'], icon: <MiscIcon/> },
  { path: '/random-number-generator', name: 'Random Number Generator', description: 'Generate a random number in a range.', category: 'Misc', component: React.lazy(() => import('../pages/misc/RandomNumberGenerator')), keywords: ['random', 'number', 'generator'], icon: <MiscIcon/> },
  { path: '/clipboard-manager', name: 'Clipboard Manager', description: 'Manage your clipboard history (session only).', category: 'Misc', component: React.lazy(() => import('../pages/misc/ClipboardManager')), keywords: ['clipboard', 'manager', 'history'], icon: <MiscIcon/> },
  { path: '/morse-code-translator', name: 'Morse Code Translator', description: 'Translate text to and from Morse code.', category: 'Misc', component: React.lazy(() => import('../pages/misc/MorseCodeTranslator')), keywords: ['morse', 'code', 'translator'], icon: <MiscIcon/> },
  { path: '/time-zone-converter', name: 'Time Zone Converter', description: 'Convert time between different time zones.', category: 'Misc', component: React.lazy(() => import('../pages/misc/TimeZoneConverter')), keywords: ['time', 'zone', 'converter'], icon: <MiscIcon/> },
  { path: '/ip-info-lookup', name: 'IP Info Lookup', description: 'Get information about an IP address.', category: 'Misc', component: React.lazy(() => import('../pages/misc/IpInfoLookup')), keywords: ['ip', 'info', 'lookup'], icon: <MiscIcon/> },
  { path: '/calculator', name: 'Calculator', description: 'A simple online calculator.', category: 'Misc', component: React.lazy(() => import('../pages/misc/Calculator')), keywords: ['calculator', 'math'], icon: <MiscIcon/> },
  { path: '/binary-translator', name: 'Binary Translator', description: 'Translate text to and from binary code.', category: 'Misc', component: React.lazy(() => import('../pages/misc/BinaryTranslator')), keywords: ['binary', 'translator', 'text'], icon: <MiscIcon/> },
];